// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfnZwutRL7oJEICbUF4k_1tK9JAMxzns',
    appId: '1:462878221025:web:327c5feef92260b56ecda0',
    messagingSenderId: '462878221025',
    projectId: 'gp-db-2023-b1591',
    authDomain: 'gp-db-2023-b1591.firebaseapp.com',
    storageBucket: 'gp-db-2023-b1591.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKrvNiRk3QRSXP46Uf8Y44hie5xpt09Fk',
    appId: '1:462878221025:android:680560a772f009c26ecda0',
    messagingSenderId: '462878221025',
    projectId: 'gp-db-2023-b1591',
    storageBucket: 'gp-db-2023-b1591.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Bxun7scXwNuomwUuBkLxM8v3FAhvfEE',
    appId: '1:462878221025:ios:acf6dba1e6d112796ecda0',
    messagingSenderId: '462878221025',
    projectId: 'gp-db-2023-b1591',
    storageBucket: 'gp-db-2023-b1591.appspot.com',
    iosBundleId: 'com.example.yourStory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Bxun7scXwNuomwUuBkLxM8v3FAhvfEE',
    appId: '1:462878221025:ios:74bebc080e7007206ecda0',
    messagingSenderId: '462878221025',
    projectId: 'gp-db-2023-b1591',
    storageBucket: 'gp-db-2023-b1591.appspot.com',
    iosBundleId: 'com.example.yourStory.RunnerTests',
  );
}
